"""add processed field

Revision ID: bc4f4106061a
Revises: 
Create Date: 2024-12-15 13:33:54.426002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4f4106061a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('processed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_messages_processed'), 'messages', ['processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_processed'), table_name='messages')
    op.drop_column('messages', 'processed')
    # ### end Alembic commands ###
